name: Lint and Test Charts

on: pull_request

env:
  HELM_CHART_PATH: infra/charts/test-chart

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run chart-testing (template)
        run: |
          currentDir=$(pwd)
          echo $HELM_CHART_PATH
          cd $currentDir/$HELM_CHART_PATH
          ls | grep values.yaml > valuesList.txt
          sed -i '/valuesList.txt/d' valuesList.txt
          while read t; do
            echo templating using $t
            helm template -f $t . 1> /dev/null
          done < valuesList.txt
