name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1
          
      - name: Run helm template
        if: steps.list-changed.outputs.changed == 'true'
        run: | ## Will only run if there is chart changes recorded from previous step
          currentDir=$(pwd)
          while read p; do
            echo "Running helm template in $currentDir/$p"
            cd $currentDir/$p
            ls | grep values.yaml > valuesList.txt
            sed -i '/valuesList.txt/d' valuesList.txt
            while read t; do
              echo templating using $t 
              helm template -f $t . 1> /dev/null
            done < valuesList.txt
          done <chartList.txt
