name: Lint and Test Charts

on: pull_request

env:
  HELM_CHART_PATH: infra/charts/test-chart

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run chart-testing (template)
        run: |
          helm template -f $HELM_CHART_PATH/values.yaml $HELM_CHART_PATH 1> /dev/null
