name: Test (helm-template)

on:
  push:
    branches:
      - main
    paths:
      - "infra/charts/test-chart/**"
  pull_request:
    branches:
      - main
    paths:
      - "infra/charts/test-chart/**"

env:
  HELM_CHART_DIR: ./infra/charts/test-chart

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run helm template
        run: |
          helm template -f $HELM_CHART_DIR/values.yaml . 1> /dev/null
